import type { FileGenerationResult, FileStrategy } from "@danielbiegler/vendure-plugin-invoices";
import { Logger, RequestContext } from "@vendure/core";
import { InvoiceFonts, InvoiceLogo, renderInvoice } from "./render";
import { DeepPartialTheme } from "./theme";
import { PDFKIT_SNAPSHOT_VERSION, PdfkitSnapshot } from "./types";

export const loggerCtx = "PdfkitInvoiceStrategy";

export interface PdfkitFileStrategyOptions {
  theme?: DeepPartialTheme;
  fonts?: InvoiceFonts;
  logo?: InvoiceLogo;

  /**
   * @default `${sequentialId}.pdf`
   */
  filename?: (sequentialId: string, snapshot: PdfkitSnapshot) => string;

  /**
   * Runs against the finished document before the page footers are drawn. Use it for
   * anything the built-in template does not cover, e.g. a "paid" watermark.
   */
  decorate?: (doc: PDFKit.PDFDocument, snapshot: PdfkitSnapshot) => void | Promise<void>;

  /**
   * Leaves the PDF content streams uncompressed, which makes the text extractable by
   * simple tooling at the cost of a considerably larger file.
   *
   * @default true
   */
  compress?: boolean;
}

/**
 * Renders the snapshot produced by {@link PdfkitSnapshotStrategy} into a PDF.
 *
 * Pair the two: this strategy reads nothing but the snapshot, which is what allows an
 * invoice from years ago to be regenerated byte for byte.
 */
export class PdfkitFileStrategy implements FileStrategy<PdfkitSnapshot> {
  constructor(private options: PdfkitFileStrategyOptions = {}) {}

  async generate(
    ctx: RequestContext,
    sequentialId: string,
    snapshot: PdfkitSnapshot,
  ): Promise<FileGenerationResult> {
    if (snapshot?.version !== PDFKIT_SNAPSHOT_VERSION) {
      // Older rows stay renderable on a best-effort basis; refusing outright would
      // break re-generation of exactly the documents that matter most.
      Logger.warn(
        `Snapshot of "${sequentialId}" has version "${snapshot?.version}", expected "${PDFKIT_SNAPSHOT_VERSION}"`,
        loggerCtx,
      );
    }

    const buffer = await renderInvoice(snapshot, {
      theme: this.options.theme,
      fonts: this.options.fonts,
      logo: this.options.logo,
      decorate: this.options.decorate,
      compress: this.options.compress,
    });

    return {
      filename: this.options.filename?.(sequentialId, snapshot) ?? `${sequentialId}.pdf`,
      buffer,
    };
  }
}
